# This is a basic workflow to help you get started with Actions

name: Staging-Publish-To-Unified-Catalog

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish-petstore:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: axway.jfrog.io/ampc-public-docker-release/node-axway-cli
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a set of commands using the runners shell
    - uses: actions/checkout@v2
    - name: update-cli
      run: |
            axway pm install @axway/axway-central-cli@$CLI_VERSION
            gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.LARGE_SECRET_PASSPHRASE }} --output $HOME/key.pem key.pem.gpg
            axway config set auth.tokenStoreType file
    - name: petstore-publish
      run: |
            ./create.sh -did=$DOSA_CLIENT_ID -pk=$HOME/key.pem -cet=$CENTRAL_ENV_TYPE -cen=$CENTRAL_ENV_NAME -rp=$RESOURCES_PATH
    env:
      CLI_VERSION: 1.5.0
      RESOURCES_PATH: resources/petstore-sample
      CATALOG_DOCUMENTATION_FILE_NAME: catalogDocumentation.md
      IMAGE_LOCATION_FILE_NAME: image.png
      CENTRAL_ENV_TYPE: staging
      VERSION: alpha
      SERVICE_HOST: petstore.swagger.io
      SERVICE_HOST_BASEPATH: /v2
      CENTRAL_ENV_NAME: petstore-staging
      DOSA_CLIENT_ID: DOSA_75a1be4d2d0e4f24acc484ccb9284bf3
      SPECIFICATION_URL: https://petstore.swagger.io/v2/swagger.json
      CATALOG_ITEM_STATE: PUBLISHED
      CATALOG_ITEM_VISIBILITY: RESTRICTED
      OWNING_TEAM_NAME: "Dev Team"


